version: '3'
services:
#  web:
#    build: .
#    ports:
#      - "50000:5000"
#    env_file:
#      - .env
#    depends_on:
#      - redis
#      - postgres
#  celery:
#    build: .
#    command: celery -A app.runcelery.celery worker --loglevel=INFO
#    env_file:
#      - .env
#    depends_on:
#      - redis
#      - postgres
  postgres:
    image: postgres:latest
    container_name: postgres12
    ports:
      - "54322:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:7
    restart: always
    ports:
      - '16379:6379'
    volumes:
      - cache:/data
  mongo:
    image: mongo:latest
    container_name: mongo1
    ports:
      - "27017:27017"
volumes:
  pgdata:
  cache:
